// Generated by CoffeeScript 1.9.2
var exe, expect, ql;

expect = require('chai').expect;

ql = require('odoql');

ql = ql();

exe = require('../');

exe = exe();

describe('fill', function() {
  it('should fill in a parameter for concat', function(done) {
    var query;
    query = ql('test').concat(ql.param('param1')).fill({
      param1: 'name'
    }).query();
    return exe.build(query)(function(err, result) {
      expect(err).to.be["null"];
      expect(result).to.equal('testname');
      return done();
    });
  });
  return it('should apply to a deep calculation', function(done) {
    var query;
    query = ql('param1').param().add(1).mult(ql.param('param2')).div(3).fill({
      param1: 5,
      param2: 2
    }).query();
    return exe.build(query)(function(err, result) {
      expect(err).to.be["null"];
      expect(result).to.equal(4);
      return done();
    });
  });
});
