// Generated by CoffeeScript 1.9.1
var eq;

eq = require('./eq');

module.exports = function(a, b) {
  var key, query, result;
  result = {};
  for (key in b) {
    query = b[key];
    if ((a[key] != null) && query.__q !== 'nocache' && eq(a[key], query)) {
      continue;
    }
    result[key] = query;
  }
  return result;
};
