// Generated by CoffeeScript 1.9.2
var eq, hasoption;

eq = require('./eq');

hasoption = require('./hasoption');

module.exports = function(a, b) {
  var key, query, result;
  result = {};
  for (key in b) {
    query = b[key];
    if ((a[key] != null) && !hasoption(query, 'nocache') && eq(a[key], query)) {
      continue;
    }
    result[key] = query;
  }
  return result;
};
