// Generated by CoffeeScript 1.9.1
var split;

split = require('./split');

module.exports = function(exe, queries) {
  var fn, key, keys, query, ref, result;
  queries = split(exe, queries);
  result = [];
  ref = queries.local;
  fn = function(key, query) {
    query = exe.build(query);
    return result.push({
      keys: [key],
      query: function(cb) {
        return query(function(err, res) {
          var returnresult;
          if (err != null) {
            returnresult = {};
            returnresult[key] = err;
            return cb(returnresult);
          }
          returnresult = {};
          returnresult[key] = res;
          return cb(null, returnresult);
        });
      }
    });
  };
  for (key in ref) {
    query = ref[key];
    fn(key, query);
  }
  keys = Object.keys(queries.remote);
  if (keys.length === 0) {
    return result;
  }
  result.push({
    keys: keys,
    query: exe.providers.__dynamic(exe, {
      __q: '__dynamic',
      __p: keys,
      __s: queries.remote
    })
  });
  return result;
};
