// Generated by CoffeeScript 1.9.2
var extend, visit;

extend = require('extend');

visit = require('../visit');

module.exports = {
  unary: {
    param: function(exe, params) {
      throw new Error('Parameters should not be executed');
    }
  },
  params: {
    fill: function(exe, params) {
      var getparams;
      getparams = exe.build(params.__p);
      return function(callback) {
        return getparams(function(err, properties) {
          var fillparams;
          if (err != null) {
            return callback(err);
          }
          fillparams = function(node, cb) {
            var getref;
            if ((node.__q == null) || node.__q !== 'param') {
              return cb();
            }
            getref = exe.build(node.__s);
            return getref(function(err, res) {
              if (err != null) {
                throw new Error(err);
              }
              if (properties[res] != null) {
                return cb(properties[res]);
              }
              return cb();
            });
          };
          return visit(params.__s, fillparams, function(filled) {
            var getref;
            getref = exe.build(filled);
            return getref(function(err, result) {
              if (err != null) {
                return callback(err);
              }
              return callback(null, result);
            });
          });
        });
      };
    }
  }
};
